name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: AbirChakraborty1703
          outputs: |
            dist/snake.svg?palette=github
            dist/snake-dark.svg?palette=github-dark&color_snake=white&color_dots=white,lightgray,gray,darkgray


      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
