name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: AbirChakraborty1703
          outputs: |
            dist/snake.svg?palette=github-light&color_snake=#228B22&color_dots=#32CD32,#228B22,#90EE90,#00FF00,#7CFC00,#ADFF2F,#9AFF9A,#98FB98,#00FF7F,#00FA9A
            dist/snake-dark.svg?palette=github-dark&color_snake=#00FF00&color_dots=#32CD32,#228B22,#90EE90,#00FF00,#7CFC00,#ADFF2F,#9AFF9A,#98FB98,#00FF7F,#00FA9A


      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
